---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/notebooks":
    get:
      summary: list notebooks
      responses:
        '200':
          description: successful
    post:
      summary: create notebook
      responses:
        '200':
          description: successful
  "/api/v1/notebooks/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show notebook
      responses:
        '200':
          description: successful
    patch:
      summary: update notebook
      responses:
        '200':
          description: successful
    put:
      summary: update notebook
      responses:
        '200':
          description: successful
    delete:
      summary: delete notebook
      responses:
        '200':
          description: successful
  "/api/v1/notebooks/{notebook_id}/notes":
    parameters:
    - name: notebook_id
      in: path
      description: notebook_id
      required: true
      schema:
        type: string
    get:
      summary: list notes
      responses:
        '200':
          description: successful
    post:
      summary: create note
      responses:
        '200':
          description: successful
  "/api/v1/notebooks/{notebook_id}/notes/{id}":
    parameters:
    - name: notebook_id
      in: path
      description: notebook_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show note
      responses:
        '200':
          description: successful
    patch:
      summary: update note
      responses:
        '200':
          description: successful
    put:
      summary: update note
      responses:
        '200':
          description: successful
    delete:
      summary: delete note
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
